variables:
  - name: solution
    value: SourcemapTools.sln
  - name: build_configuration
    value: Release
  - name: assemblyVersion
    value: 1.0.0
  - name: packageVersion
    value: 1.0.1
  - name: nugetDevVersion
    value: 1.0.2

trigger:
  - master
  - release
pr:
  branches:
    include:
    - '*'

stages:

- stage: ''
  displayName: ''
  jobs:
  - job: main_job
    pool:
      vmImage: 'windows-2019'
    displayName: 'SourceMap Tools'

    steps:

#########
# BUILD #
#########
    - task: NuGetToolInstaller@1
      displayName: Install latest nuget tools

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/ci/SetVersion.ps1'
        workingDirectory: '$(Build.SourcesDirectory)'
        arguments: -path $(Build.SourcesDirectory)/Shared.props -version $(assemblyVersion)
      displayName: Update assembly version

    - task: MSBuild@1
      inputs:
        solution: '$(solution)'
        configuration: '$(build_configuration)'
        msbuildArguments: '/t:Restore;Rebuild -m /p:ContinuousIntegrationBuild=true'
      displayName: Build solution

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(Build.SourcesDirectory)/tests/SourcemapTools.UnitTests/SourcemapTools.UnitTests.csproj'
        publishWebProjects: false
        zipAfterPublish: false
        arguments: -f netcoreapp2.1 -c $(build_configuration)
        nobuild: true
      displayName: Publish test project for netcoreapp2.1

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(Build.SourcesDirectory)/tests/SourcemapTools.UnitTests/SourcemapTools.UnitTests.csproj'
        publishWebProjects: false
        zipAfterPublish: false
        arguments: -f netcoreapp3.1 -c $(build_configuration)
        nobuild: true
      displayName: Publish test project for netcoreapp3.1

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(Build.SourcesDirectory)/tests/SourcemapTools.UnitTests/SourcemapTools.UnitTests.csproj'
        publishWebProjects: false
        zipAfterPublish: false
        arguments: -f net5.0 -c $(build_configuration)
        nobuild: true
      displayName: Publish test project for net 5
########
# TEST #
########
    - task: UseDotNet@2
      displayName: 'Install .net core 2.1'
      inputs:
        packageType: sdk
        version: 2.1.x

    - task: UseDotNet@2
      displayName: 'Install .net core 3.1'
      inputs:
        packageType: sdk
        version: 3.1.x

    - task: UseDotNet@2
      displayName: 'Install .net 5'
      inputs:
        packageType: sdk
        version: 5.x

    - script: dotnet test $(Build.SourcesDirectory)\tests\SourcemapTools.UnitTests\bin\Release\net48\SourcemapTools.UnitTests.dll /Framework:net48 /logger:trx
      displayName: 'Tests: .NET FX 4.8'

    - task: PublishTestResults@2
      inputs:
        testRunner: VsTest
        testResultsFiles: '**/*.trx'
        testRunTitle: 'NETFX 4.8'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    - task: DeleteFiles@1
      inputs:
        contents: '**/*.trx'
      displayName: 'Cleanup'
      condition: succeededOrFailed()

    - script: dotnet test $(Build.SourcesDirectory)\tests\SourcemapTools.UnitTests\bin\Release\netcoreapp2.1\SourcemapTools.UnitTests.dll /Framework:netcoreapp2.1 /logger:trx
      displayName: 'Tests: .NET Core 2.1'
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      inputs:
        testRunner: VsTest
        testResultsFiles: '**/*.trx'
        testRunTitle: '.NET CORE 2.1'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    - task: DeleteFiles@1
      inputs:
        contents: '**/*.trx'
      displayName: 'Cleanup'
      condition: succeededOrFailed()

    - script: dotnet test $(Build.SourcesDirectory)\tests\SourcemapTools.UnitTests\bin\Release\netcoreapp3.1\SourcemapTools.UnitTests.dll /Framework:netcoreapp3.1 /logger:trx
      displayName: 'Tests: .NET Core 3.1'
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      inputs:
        testRunner: VsTest
        testResultsFiles: '**/*.trx'
        testRunTitle: '.NET CORE 3.1'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    - task: DeleteFiles@1
      inputs:
        contents: '**/*.trx'
      displayName: 'Cleanup'
      condition: succeededOrFailed()

    - script: dotnet test $(Build.SourcesDirectory)\tests\SourcemapTools.UnitTests\bin\Release\net5.0\SourcemapTools.UnitTests.dll /Framework:net5.0 /logger:trx
      displayName: 'Tests: .NET 5'
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      inputs:
        testRunner: VsTest
        testResultsFiles: '**/*.trx'
        testRunTitle: '.NET 5'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    - task: DeleteFiles@1
      inputs:
        contents: '**/*.trx'
      displayName: 'Cleanup'
      condition: succeededOrFailed()

#################
# PUBLISH NUGET #
#################
    - powershell: echo "##vso[task.setvariable variable=packageVersion]$(nugetDevVersion)-rc.$(Build.BuildId)"
      condition: eq(variables['Build.SourceBranchName'], 'master')
      displayName: Update nuget version

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/ci/BuildNuspecs.ps1'
        workingDirectory: '$(Build.SourcesDirectory)'
        arguments: -path $(Build.SourcesDirectory)/ci/SourceMapTools.nuspec -version $(packageVersion) -branch $(Build.SourceBranchName)
      displayName: Update nuspecs
      condition: or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'release'))

    - task: CmdLine@2
      inputs:
        script: nuget.exe Pack $(Build.SourcesDirectory)\ci\SourceMapTools.nuspec -OutputDirectory $(Build.SourcesDirectory)\ci
        workingDirectory: $(Build.SourcesDirectory)/ci
      displayName: Build nuget for Azure Artifacts
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

    - task: CmdLine@2
      inputs:
        script: nuget.exe Pack $(Build.SourcesDirectory)\ci\SourceMapTools.nuspec -OutputDirectory $(Build.SourcesDirectory)\ci -Symbols -SymbolPackageFormat snupkg
        workingDirectory: $(Build.SourcesDirectory)/ci
      displayName: Build nuget for Nuget.org
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'release'))

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/ci/SourceMapTools.*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'sourcemaptools/sourcemap-tools'
      displayName: Publish to Azure Artifacts feed
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/ci/SourceMapTools.*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'sourcemap-tools at nuget.org'
      displayName: Publish to Nuget.org
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'release'))

